[package]
name = "riscvm"
version = "0.0.1"
authors = ["Oliver Lau <oliver@ersatzworld.net>"]
license = "MIT"

[dependencies]
thiserror = "^1.0"
regex = "^1.5"
pest = "2.0"
pest_derive = "2.0"
log = "^0.4.17"
env_logger = "^0.9"
